[package]
name = "zoho-api"
description = "An API client for Zoho"
version = "0.1.0"
authors = ["Augustus Mayo <augustus@oxide.computer>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/cio"
documentation = "https://docs.rs/zoho-api"

[[bin]]
name = "generator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }