{
 "title": "GitHub Data",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "`check_suite` and `check_run` events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "`check_run` failures per repo per day",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"check_run\")\n  |> filter(fn: (r) => r[\"action\"] == \"completed\")\n  |> filter(fn: (r) => r[\"conclusion\"] == \"failure\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      repo_name: r.repo_name,\n      _value: r._value,\n    }))\n   |> window(every:24h, createEmpty: true)\n   |> count()\n   |> group(columns: [\"repo_name\"], mode: \"by\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`check_suite` time to successful completion",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"github_transformed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"check_suite\")\n  |> unique(column: \"github_id\")\n  |> filter(fn: (r) => (uint(v: r._time) - uint(v: r._value)) < (1000000000 * 60 * 30) )\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: uint(v: r._time) - uint(v: r._value),\n      repo_name: r.repo_name,\n      _sha: r.sha,\n      _link: \"https://github.com/oxidecomputer/\" + r.repo_name + \"/commits/\" + r.sha, \n      slug: r.slug,\n    })\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`check_run` time to successful completion",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"github_transformed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"check_run\")\n  |> unique(column: \"github_id\")\n  |> filter(fn: (r) => (uint(v: r._time) - uint(v: r._value)) < (1000000000 * 60 * 3) )\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: uint(v: r._time) - uint(v: r._value),\n      repo_name: r.repo_name,\n      _sha: r.sha,\n      _link: \"https://github.com/oxidecomputer/\" + r.repo_name + \"/commits/\" + r.sha, \n      app_slug: r.app_slug,\n      _name: r.name,\n    })\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`pull_request_review_comment` events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "`pull_request_review_comment` events over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pull_request_review_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`pull_request_review_comment` created by `sender`",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "pull_request_review_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "created" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request_review_comment` created by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "pull_request_review_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "created" },
      { "condition": "AND", "key": "sender", "operator": "!=", "value": "select tag value" }
     ]
    }
   ]
  },
  { "title": "`issue_comment` events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "`issue_comment` events over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "issue_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`issue_comment` created by `sender`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "issue_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "created" }
     ]
    }
   ]
  },
  {
   "title": "`issue_comment` created by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "issue_comment",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "created" }
     ]
    }
   ]
  },
  { "title": "`issues` events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "`issues` events over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "issues",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "time to `issues` closed",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "dtdurationms", "label": "duration of time to close" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "timeOpened = from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"issues\")\n  |> filter(fn: (r) => r[\"action\"] == \"opened\")\n\ntimeClosed = from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"issues\")\n  |> filter(fn: (r) => r[\"action\"] == \"closed\")\n\njoin(\n  tables: {opened:timeOpened, closed:timeClosed},\n  on: [\"number\", \"repo_name\"]\n)\n|> map(fn: (r) => ({\n      _time: r._time_closed,\n      _value: (uint(v: r._time_closed) - uint(v: r._time_opened)) / uint(v: 1000000),\n      duration_string: string(v: duration(v: uint(v: r._time_closed) - uint(v: r._time_opened))),\n      repo_name: r.repo_name,\n      number: r.number,\n      link: \"https://github.com/oxidecomputer/\" + r.repo_name + \"/issues/\" + r.number\n    })\n  )\n  |> sort(columns:[\"_value\"], desc: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`issues` opened by `sender`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "issues",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "opened" }
     ]
    }
   ]
  },
  {
   "title": "`issues` closed by `sender`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "issues",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" }
     ]
    }
   ]
  },
  {
   "title": "`issues` opened by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "issues",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "opened" }
     ]
    }
   ]
  },
  {
   "title": "`issues` closed by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "issues",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" }
     ]
    }
   ]
  },
  { "title": "`pull_request` events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 } },
  {
   "title": "`pull_request` events over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "time to `pull_request` merged",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 263 },
   "yaxes": [
    { "format": "dtdurationms", "label": "duration of time to close" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "timeOpened = from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pull_request\")\n  |> filter(fn: (r) => r[\"action\"] == \"opened\")\n\ntimeClosed = from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pull_request\")\n  |> filter(fn: (r) => r[\"action\"] == \"closed\")\n  |> filter(fn: (r) => r[\"merged\"] == true)\n\njoin(\n  tables: {opened:timeOpened, closed:timeClosed},\n  on: [\"number\", \"repo_name\"]\n)\n|> map(fn: (r) => ({\n      _time: r._time_closed,\n      _value: (uint(v: r._time_closed) - uint(v: r._time_opened)) / uint(v: 1000000),\n      duration_string: string(v: duration(v: uint(v: r._time_closed) - uint(v: r._time_opened))),\n      repo_name: r.repo_name,\n      number: r.number,\n      link: \"https://github.com/oxidecomputer/\" + r.repo_name + \"/pull/\" + r.number\n    })\n  )\n  |> sort(columns:[\"_value\"], desc: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`pull_request` opened by `sender`",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 283 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "opened" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request` merged by `sender`",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" },
      { "condition": "AND", "key": "merged", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request` closed (but not merged) by `sender`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 319 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" },
      { "condition": "AND", "key": "merged", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request` opened by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 339 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "opened" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request` closed (but not merged) by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 359 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" },
      { "condition": "AND", "key": "merged", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "`pull_request` merged by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 379 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "pull_request",
     "select": [
      [
       { "params": [ "github_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "closed" },
      { "condition": "AND", "key": "merged", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  { "title": "`push` events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 399 } },
  {
   "title": "`push` events over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 400 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "push",
     "query": "SELECT count(distinct(\"sha\")) FROM \"github-webhooks-rp\".\"push\" WHERE $timeFilter AND (\"added\" !~ /pdfs/ AND \"modified\" !~ /pdfs/ AND \"removed\" !~ /pdfs/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sha" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`push` events by `sender`",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 407 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "push",
     "query": "SELECT count(distinct(\"sha\")) FROM \"github-webhooks-rp\".\"push\" WHERE $timeFilter AND (\"added\" !~ /pdfs/ AND \"modified\" !~ /pdfs/ AND \"removed\" !~ /pdfs/) GROUP BY \"sender\"",
     "select": [
      [
       { "params": [ "sha" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "`push` events by `repo_name`",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 426 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" }
     ],
     "measurement": "push",
     "query": "SELECT count(distinct(\"sha\")) FROM \"github-webhooks-rp\".\"push\" WHERE $timeFilter AND (\"added\" !~ /pdfs/ AND \"modified\" !~ /pdfs/ AND \"removed\" !~ /pdfs/) GROUP BY \"repo_name\"",
     "select": [
      [
       { "params": [ "sha" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "longest commit messages",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 443 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\nimport \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"github_webhooks\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"push\")\n  |> schema.fieldsAsCols()\n  |> map(fn: (r) => ({\n        _sender: r.sender,\n        message_len: strings.strlen(v: r.message),\n        _message: r.message,\n        _link: \"https://github.com/oxidecomputer/\" + r.repo_name + \"/commit/\" + r.sha,\n    })\n  )\n  |> sort(columns: [\"message_len\"], desc: true)\n  |> limit(n:50, offset: 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sum of `additions` by sender",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 462 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket:\"github_webhooks\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"push\")\n    |> schema.fieldsAsCols()\n    |> filter(fn: (r) => r.additions > 0)\n    |> group(columns: [\"sender\"], mode: \"by\")\n    |> sum(column: \"additions\")\n    |> map(fn: (r) => ({ \n        _sender: r.sender,\n        additions: r.additions\n      }))\n    |> sort(columns: [\"additions\"], desc: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sum of `deletions` by sender",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 462 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket:\"github_webhooks\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"push\")\n    |> schema.fieldsAsCols()\n    |> filter(fn: (r) => r.deletions > 0)\n    |> group(columns: [\"sender\"], mode: \"by\")\n    |> sum(column: \"deletions\")\n    |> map(fn: (r) => ({ \n        _sender: r.sender,\n        deletions: r.deletions\n      }))\n    |> sort(columns: [\"deletions\"], desc: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "most popular commit messages",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 476 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "push",
     "query": "from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"push\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r.message,\n      _repo_name: r.repo_name,\n      _sender: r.sender,\n      _sha: r.sha,\n      _count: 1,\n    })\n  )\n  |> unique(column: \"_sha\")\n  |> group(columns: [\"_value\"], mode:\"by\")\n  |> stateCount(\n    fn: (r) => r._count == 1,\n    column: \"count\"\n  )\n  |> max(column: \"count\")\n  |> map(fn: (r) => ({\n      count: r.count,\n      message: r._value,\n    })\n  )\n  |> filter(fn: (r) => r.message !~ /^Updating file content .*pdfs.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Updating .*rendered PDF.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Run .*make.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Creating .*meeting notes.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Updating .*meeting notes.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message != \"Update README Table\", onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message != \"docs: Update TOC\", onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Run terraform apply.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message !~ /^Merge branch.*/, onEmpty: \"drop\")\n  |> filter(fn: (r) => r.message != \"Update team members\", onEmpty: \"drop\")\n  |> sort(columns: [\"count\"], desc: true)\n  |> limit(n:50, offset: 0)",
     "select": [
      [
       { "params": [ "sha" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "top senders with \"typo\" in their commit messages",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 476 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "push",
     "query": "from(bucket: \"github_webhooks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"push\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r.message,\n      _repo_name: r.repo_name,\n      _sender: r.sender,\n      _sha: r.sha,\n      _count: 1,\n    })\n  )\n  |> unique(column: \"_sha\")\n  |> filter(fn: (r) => r._value =~ /.*typo.*/)\n  |> group(columns: [\"_sender\"], mode:\"by\")\n  |> stateCount(\n    fn: (r) => r._count == 1,\n    column: \"count\"\n  )\n  |> max(column: \"count\")\n  |> map(fn: (r) => ({\n      count: r.count,\n      sender: r._sender,\n    })\n  )\n  |> sort(columns: [\"count\"], desc: true)",
     "select": [
      [
       { "params": [ "sha" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}