use std::env;
use std::path::Path;

use clap::{value_t, ArgMatches};
use handlebars::Handlebars;

use crate::utils::{read_config_from_files, write_file};

struct Table {
    pub template: String,
    pub path: String,
}

pub fn cmd_tables_run(cli_matches: &ArgMatches) {
    // Get the current working directory.
    let curdir = env::current_dir().unwrap();
    let curdir_str = curdir.to_str().unwrap();

    // Get the directory passed or default to the current directory.
    let dir =
        value_t!(cli_matches, "dir", String).unwrap_or(curdir_str.to_string());

    // Create the PathBuf.
    let output_dir = Path::new(&dir);

    // Get the config.
    let config = read_config_from_files(cli_matches);

    // Initialize handlebars.
    let handlebars = Handlebars::new();

    // Create the tables vector.
    let tables = vec![
        Table {
            template: TEMPLATE_GROUPS.to_string(),
            path: "directory/groups/README.md".to_string(),
        },
        Table {
            template: TEMPLATE_LINKS.to_string(),
            path: "links/README.md".to_string(),
        },
        Table {
            template: TEMPLATE_PEOPLE.to_string(),
            path: "directory/people/README.md".to_string(),
        },
    ];

    for table in tables {
        let rendered = handlebars
            .render_template(&table.template, &config)
            .unwrap();

        // Join it with the directory to save the files in.
        let file = output_dir.join(table.path.to_string());

        write_file(file, rendered);
    }
}

static TEMPLATE_GROUPS: &'static str = "<!-- THIS WHOLE FILE IS GENERATED FROM THE CONFIGS REPO in src/tables.rs DO NOT EDIT IT DIRECTLY -->
# Groups

Mailing list groups for the company.

<!-- START doctoc -->
<!-- END doctoc -->

| Name | Email | Description | External Members Allowed? | Who can post | Who can view | Who can join | Who can discover |
| ---- | ----- | ----------- | ------------------------- |--------------|--------------|--------------|------------------|{{#each this.groups}}
| [{{ this.name }}](https://groups.google.com/a/oxidecomputer.com/forum/#!forum/{{ this.name }}) | [`{{ this.name }}@oxide.computer`](mailto:{{ this.name }}@oxide.computer) | {{ this.description }} | `{{ this.allow_external_members }}` | `{{ this.who_can_post_message }}` | `{{ this.who_can_view_group }}` | `{{ this.who_can_join }}` | `{{ this.who_can_discover_group }}` |{{/each}}

To edit anything in this table, email [jess@oxide.computer](mailto:jess@oxide.computer).
This whole file is automatically generated by `configs` from
[oxidecomputer/configs](https://github.com/oxidecomputer/configs), DO NOT edit
it directly.";

static TEMPLATE_LINKS: &'static str = "<!-- THIS WHOLE FILE IS GENERATED FROM THE CONFIGS REPO in src/tables.rs DO NOT EDIT IT DIRECTLY -->
# Links

Helpful links and resources for members of the company.

<!-- START doctoc -->
<!-- END doctoc -->

## GitHub Repos

We have a nice way to easily link to any repository we have in the
`oxidecomputer` organization on GitHub.

```
https://{repo}.git.oxide.computer
```

OR

```
https://git.oxide.computer/{repo}
```

An example of this is: [tockilator.git.oxide.computer](https://tockilator.git.oxide.computer)

## RFDs

We have a nice way to easily link to any RFD in the [rfd](https://github.com/oxidecomputer/rfd) repo. This link updates when the file is merged into master, so you can consider it a safe link to use to link to an RFD that might move from a branch to master after being merged.

```
https://{number}.rfd.oxide.computer
```

OR

```
https://rfd.oxide.computer/{number}
```

An example of this is: [4.rfd.oxide.computer](https://4.rfd.oxide.computer)

If you are trying to get to the pull request for the RFD you can use:

```
https://{number}.rfd.oxide.computer/discussion
```

OR

```
https://rfd.oxide.computer/{number}/discussion
```

You can also view rendered versions of RFDs at [https://rfd.shared.oxide.computer/](https://rfd.shared.oxide.computer).  For more on this, see [this README](https://github.com/oxidecomputer/rfd/blob/rendered/README.md).

## Internal Resources

| Link | Description | Aliases |
| ---- | ----------- |---------|{{#each this.links}}
| [{{ @key }}.corp.oxide.computer](https://{{ @key }}.corp.oxide.computer) | {{ this.description }} | {{#each this.aliases}}[{{this}}.corp.oxide.computer](https://{{this}}.corp.oxide.computer) {{/each}} |{{/each}}

To edit anything in this table, email [jess@oxide.computer](mailto:jess@oxide.computer).
This whole file is automatically generated by `configs` from
[oxidecomputer/configs](https://github.com/oxidecomputer/configs), DO NOT edit
it directly. Instead make your changes to the [links.toml](https://github.com/oxidecomputer/configs/blob/master/configs/links.toml) file.";

static TEMPLATE_PEOPLE: &'static str = "<!-- THIS WHOLE FILE IS GENERATED FROM THE CONFIGS REPO in src/tables.rs DO NOT EDIT IT DIRECTLY -->
# People

Members of the company.

<!-- START doctoc -->
<!-- END doctoc -->

| Name | Email | Email Aliases | GitHub | Chat | Zoom URL | Twitter |
| ---- | ----- | ------------- | ------ | ---- | -------- | ------- |{{#each this.users}}
| {{ this.first_name }} {{ this.last_name }} | [`{{ this.username }}@oxide.computer`](mailto:{{ this.username }}@oxide.computer) | `{{ this.aliases }}` | {{#if this.github}}[@{{ this.github }}](https://github.com/{{ this.github }}){{/if}} | {{#if this.chat}}`{{ this.chat }}`{{/if}} | {{#if this.github}}[oxide.zoom.us/my/{{ this.github }}](https://oxide.zoom.us/my/{{ this.github }}){{/if}} | {{#if this.twitter}}[@{{ this.twitter }}](https://twitter.com/{{ this.twitter }}){{/if}} |{{/each}}

To edit anything in this table, email [jess@oxide.computer](mailto:jess@oxide.computer).
This whole file is automatically generated by `configs` from
[oxidecomputer/configs](https://github.com/oxidecomputer/configs), DO NOT edit
it directly.";
