on:
  schedule:
    - cron: "0 17 * * MON"
  workflow_dispatch:
    inputs:
name: run rfd changelog
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - name: Install asciidoctor, pandoc, and pdftotext
        shell: bash
        run: |
          sudo apt update -y && sudo apt install -y \
            asciidoctor \
            libusb-1.0-0-dev \
            pandoc \
            poppler-utils \
            ruby \
          sudo gem install asciidoctor-pdf asciidoctor-mermaid rouge
          npm install @mermaid-js/mermaid-cli
          ln -s ./node_modules/.bin/mmdc /usr/local/bin/mmdc
      - name: Install SQL proxy
        shell: bash
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy \
          && chmod +x cloud_sql_proxy
      - name: Install latest nightly
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        with:
            components: rustfmt, clippy
      - name: Cache github etags
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: github-cache
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up environment
        shell: bash
        run: |
          echo "$SQL_PROXY_KEY" > ${{ github.workspace }}/sql_proxy_key
        env:
          SQL_PROXY_KEY: ${{ secrets.SQL_PROXY_KEY }}
      - name: Start the sql_proxy
        shell: bash
        run: |
          ./cloud_sql_proxy -instances=${{ secrets.INSTANCE_CONNECTION_NAME }}=tcp:5432 \
                  -credential_file=${{ github.workspace }}/sql_proxy_key &
      - name: Run cargo test
        run: |
          cargo test test_monday_cron -- --ignored
        shell: bash
        env:
          GOOGLE_KEY_ENCODED: ${{ secrets.GOOGLE_CIO_KEY_ENCODED }}
          CIO_AUTH0_CLIENT_ID: ${{ secrets.CIO_AUTH0_CLIENT_ID }}
          CIO_AUTH0_CLIENT_SECRET: ${{ secrets.CIO_AUTH0_CLIENT_SECRET }}
          CIO_DATABASE_URL: ${{ secrets.CIO_DATABASE_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          INFLUX_DB_URL: ${{ secrets.INFLUX_DB_URL }}
          INFLUX_DB_TOKEN: ${{ secrets.INFLUX_DB_TOKEN }}
          SHIPPO_API_TOKEN: ${{ secrets.SHIPPO_API_TOKEN }}
          REVAI_API_KEY: ${{ secrets.REVAI_API_KEY }}
          RUST_LOG: trace
          SENTRY_DSN: ${{secrets.WEBHOOKY_SENTRY_DSN}}
